// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TbAmoleCart struct {
	TacID         int64  `json:"tac_id"`
	TacMemberID   int32  `json:"tac_member_id"`
	TacTotalPrice int32  `json:"tac_total_price"`
	TacStatus     string `json:"tac_status"`
}

type TbAmoleCartItem struct {
	TaciID        int64 `json:"taci_id"`
	TaciCartID    int32 `json:"taci_cart_id"`
	TaciProductID int32 `json:"taci_product_id"`
	TaciQty       int32 `json:"taci_qty"`
	TaciPrice     int32 `json:"taci_price"`
}

type TbAmoleMember struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Address  string `json:"address"`
}

type TbAmoleProduct struct {
	TbapID          int64       `json:"tbap_id"`
	TbapName        string      `json:"tbap_name"`
	TbapPrice       int32       `json:"tbap_price"`
	TbapDescription string      `json:"tbap_description"`
	TbapCreatedAt   pgtype.Date `json:"tbap_created_at"`
	TbapUpdatedAt   pgtype.Date `json:"tbap_updated_at"`
}
